import json
import os

class ConfigBuilder:
    def __init__(self, filename="ControlHardwareConfig_AQuRA.json"):
        self.filename = filename
        self.config = {
            "FileOrigin": "This file is automatically generated by ControlUserIOConfigFileCreator.py. Do not edit it manually.",
            "ConfigurationName": "AQuRA",
            "PCSequenceBufferSize": 134217728,
            "LineFrequency": 50,
            "Sequencers": [],
            "Rack": [],
            "AnalogOutBoards16bit": [],
            "DigitalOutBoards": [],
            "SerialPortBoards": [],
            "DDSAD9854Boards": [],
            "DDSAD9858Boards": [],
            "DDSAD9959Boards": [],
            "AnalogInBoards12bit": []
        }

    def _add_optional_hardware_fields(self, entry, Model=None, SN=None, RackNr=None, SlotNr=None):
        optional_fields = {
            "Model": Model,
            "SN": SN,
            "RackNr": RackNr,
            "SlotNr": SlotNr
        }
        entry.update({key: value for key, value in optional_fields.items() if value is not None})
        return entry

    def RegisterSequencer(self, Id=0, Type="OpticsFoundrySequencerV1", IP="192.168.0.104", Port=7,
                          Master=True, StartDelay=10, ClockFrequencyinMHz=100, BusFrequencyinMHz=2,
                          UseExternalClock=False, UseStrobeGenerator=True, Connect=True, DebugOn = False,
                          Model=None, SN=None, RackNr=None, SlotNr=None):
        self.config["Sequencers"].append(self._add_optional_hardware_fields({
            "Id": Id,
            "Type": Type,
            "IP": IP,
            "Port": Port,
            "Master": Master,
            "StartDelay": StartDelay,
            "ClockFrequencyinMHz": ClockFrequencyinMHz,
            "BusFrequencyinMHz": BusFrequencyinMHz,
            "UseExternalClock": UseExternalClock,
            "UseStrobeGenerator": UseStrobeGenerator,
            "Connect": Connect,
            "DebugOn": DebugOn
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def RegisterAnalogOutBoard16bit(self, Sequencer=0, StartAddress=24, NumberChannels=4, Signed=True,
                                     MinVoltage=-10, MaxVoltage=10, Model=None, SN=None,
                                     RackNr=None, SlotNr=None):
        self.config["AnalogOutBoards16bit"].append(self._add_optional_hardware_fields({
            "Sequencer": Sequencer,
            "StartAddress": StartAddress,
            "NumberChannels": NumberChannels,
            "Signed": Signed,
            "MinVoltage": MinVoltage,
            "MaxVoltage": MaxVoltage
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def RegisterDigitalOutBoard(self, Sequencer=0, Address=1, NumberChannels=16, Model=None, SN=None,
                                RackNr=None, SlotNr=None):
        self.config["DigitalOutBoards"].append(self._add_optional_hardware_fields({
            "Sequencer": Sequencer,
            "Address": Address,
            "NumberChannels": NumberChannels
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def RegisterSerialPortBoard(self, Sequencer=0, Address=1, RackNr=0, SlotNr=0, Model=None, SN=None):
        self.config["SerialPortBoards"].append(self._add_optional_hardware_fields({
            "Sequencer": Sequencer,
            "Address": Address,
            "RackNr": RackNr,
            "SlotNr": SlotNr
        }, Model=Model, SN=SN))

    def RegisterDDSAD9854Board(self, Version=2, Sequencer=0, Address=132, ExternalClockFrequencyinMHz=300,
                                PLLReferenceMultiplier=1, FrequencyMultiplier=1, Model=None, SN=None,
                                RackNr=None, SlotNr=None):
        self.config["DDSAD9854Boards"].append(self._add_optional_hardware_fields({
            "Version": Version,
            "Sequencer": Sequencer,
            "Address": Address,
            "ExternalClockFrequencyinMHz": ExternalClockFrequencyinMHz,
            "PLLReferenceMultiplier": PLLReferenceMultiplier,
            "FrequencyMultiplier": FrequencyMultiplier
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def RegisterDDSAD9858Board(self, Sequencer=0, Address=50, ClockFrequencyinMHz=1200,
                                FrequencyMultiplier=1, Model=None, SN=None,
                                RackNr=None, SlotNr=None):
        self.config["DDSAD9858Boards"].append(self._add_optional_hardware_fields({
            "Sequencer": Sequencer,
            "Address": Address,
            "ClockFrequencyinMHz": ClockFrequencyinMHz,
            "FrequencyMultiplier": FrequencyMultiplier
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def RegisterDDSAD9959Board(self, Sequencer=0, Address=21, ClockFrequencyinMHz=300,
                                FrequencyMultiplier=1, AD9958 = False, Model=None, SN=None,
                                RackNr=None, SlotNr=None):
        self.config["DDSAD9959Boards"].append(self._add_optional_hardware_fields({
            "Sequencer": Sequencer,
            "Address": Address,
            "ClockFrequencyinMHz": ClockFrequencyinMHz,
            "FrequencyMultiplier": FrequencyMultiplier,
            "AD9958": "1" if AD9958 else "0"
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def RegisterAnalogInBoard12bit(self, Sequencer=0, Address=80, NumberChannels=4, MinVoltage=-10, MaxVoltage=10,
                                   Model=None, SN=None, RackNr=None, SlotNr=None):
        self.config["AnalogInBoards12bit"].append(self._add_optional_hardware_fields({
            "Sequencer": Sequencer,
            "Address": Address,
            "NumberChannels": NumberChannels,
            "MinVoltage": MinVoltage,
            "MaxVoltage": MaxVoltage
        }, Model=Model, SN=SN, RackNr=RackNr, SlotNr=SlotNr))

    def Save(self):
        used_addresses = set()
        errors = []

        def check_and_add(sequencer, address, span, name):
            if address % span != 0:
                errors.append(f"{name} at address {address} should start at a multiple of {span}.")
            for offset in range(span):
                addr = (sequencer, address + offset)
                if not (1 <= address + offset <= 251):
                    errors.append(f"{name} uses address {address + offset}, which is out of range [1, 251].")
                elif addr in used_addresses:
                    errors.append(f"Conflict: {name} at [{sequencer}, {address + offset}] already in use.")
                used_addresses.add(addr)

        for entry in self.config["AnalogOutBoards16bit"]:
            check_and_add(entry["Sequencer"], entry["StartAddress"], entry["NumberChannels"] , "AnalogOutBoard16bit")

        for entry in self.config["DigitalOutBoards"]:
            check_and_add(entry["Sequencer"], entry["Address"], 1, "DigitalOutBoard")

        for entry in self.config["SerialPortBoards"]:
            check_and_add(entry["Sequencer"], entry["Address"], 1, "SerialPortBoard")

        for entry in self.config["DDSAD9854Boards"]:
            check_and_add(entry["Sequencer"], entry["Address"], 4, "DDSAD9854Board")

        for entry in self.config["DDSAD9858Boards"]:
            check_and_add(entry["Sequencer"], entry["Address"], 4, "DDSAD9858Board")

        for entry in self.config["DDSAD9959Boards"]:
            check_and_add(entry["Sequencer"], entry["Address"], 1, "DDSAD9959Board")

        for entry in self.config["AnalogInBoards12bit"]:
            check_and_add(entry["Sequencer"], entry["Address"], 1, "AnalogInBoard12bit")

        if errors:
            print("Design rule check failed:")
            for error in errors:
                print("-", error)
            print("\nPlease fix the above issues in your RegisterXXX calls.\n")
        else:
            with open(self.filename, 'w') as f:
                json.dump(self.config, f, indent=2)
            print(f"\nConfiguration is valid. JSON file '{self.filename}' created successfully.\n")


if __name__ == "__main__":
    builder = ConfigBuilder()
    builder.RegisterSequencer(IP="192.168.0.112", Port=57978, ClockFrequencyinMHz=100, BusFrequencyinMHz=2, DebugOn = False) #0.104 #90.108
    builder.RegisterSerialPortBoard(Sequencer=0, Address=251, RackNr=0, SlotNr=1)
    analog_out_configs = [
        (24, True, -10, 10), #each of these lines configures 4 analog outputs in consecutive order of addresses
        (28, True, -10, 10),
        (32, True, -10, 10),
        (36, True, -10, 10)
    ]
    for addr, signed, minv, maxv in analog_out_configs:
        builder.RegisterAnalogOutBoard16bit(StartAddress=addr, Signed=signed, MinVoltage=minv, MaxVoltage=maxv)

    for addr in [2, 21, 3, 4, 5, 6, 7]:
        builder.RegisterDigitalOutBoard(Address=addr)

    AD9854Board0ExternalClockFrequencyinMHz = 10
    AD9854Board0PLLReferenceMultiplier = 20
    builder.RegisterDDSAD9854Board(Address=128, ExternalClockFrequencyinMHz=AD9854Board0ExternalClockFrequencyinMHz, PLLReferenceMultiplier=AD9854Board0PLLReferenceMultiplier)
    builder.RegisterDDSAD9854Board(Address=132, ExternalClockFrequencyinMHz=AD9854Board0ExternalClockFrequencyinMHz, PLLReferenceMultiplier=AD9854Board0PLLReferenceMultiplier)
    
    for addr in range(136, 172, 4):
        builder.RegisterDDSAD9854Board(Address=addr)

    for addr in [52, 56, 60, 64,  68, 72, 76, 80, 84]:# range(52, 84, 4):
        builder.RegisterDDSAD9858Board(Address=addr)
    
    for addr in [1,10]:
        builder.RegisterDDSAD9959Board(Address=addr)

    builder.Save()
